version: 2

seeds:
  - name: taxi_zone_lookup
    description: >
      Contains the lookup table for each location ID.
    columns:
      - name: locationid
        tests:
          - unique:
              severity: error